### ISSUE TITLE
Empty dev guide page

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/website#259]
See https://open-services.net/resources/developing-oslc-applications/

**Comment by berezovskyi** [comment]
@jadelkhoury @jamsden do you have an idea why does it happen?

**Comment by jadelkhoury** [comment]
How did you get to that page?
If you click on the "OSLC Developer Guide" link from the Resources page https://open-services.net/resources/, you will notice that it gets directly redirected.

i recall we made a recent change to allow such redirections, instead of a https://open-services.net that had very little information. Could this be the reason we still have this empty page? Better to remove it?

**Comment by berezovskyi** [comment]
Yep, that was Google that let me to that page. I will look into removing it.

--
/Andrew
(from phone)

2 sep. 2019 kl. 23:18 skrev Jad El-khoury <notifications@github.com<mailto:notifications@github.com>>:


How did you get to that page?
If you click on the "OSLC Developer Guide" link from the Resources page https://open-services.net/resources/, you will notice that it gets directly redirected.

i recall we made a recent change to allow such redirections, instead of a https://open-services.net that had very little information. Could this be the reason we still have this empty page? Better to remove it?

**Comment by jamsden** [comment]
I always used this link: http://oslc.github.io/developing-oslc-applications/, maybe the redirect is broken.

**Comment by berezovskyi** [comment]
There are no redirects in the Hugo site. I thought it must have been some old leftover file but then I cleaned up the /public folder in #261 but the page is still there. Will check how to remove it from the markdown content.

**Comment by berezovskyi** [comment]
I had to convert the resource page into a headless leaf bundle to make the page go away: https://gohugo.io/content-management/page-bundles/#headless-bundle
